# Makefile for a simple C program

# Compiler
CC = gcc

# Compiler flags
# CFLAGS = -Wall

# Source files
SRC = LeDuyThai_20205020_HW1.c

# Executable name
EXE = LeDuyThai_20205020_HW1.exe

all: $(EXE)

$(EXE): $(SRC)
	$(CC) $(CFLAGS) -o $(EXE) $(SRC)

clean:
	rm -f $(EXE)

.PHONY: all clean
